<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$redirect = $storeManager->getStore()->getBaseUrl();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customer = $block->getCustomer();
?>
<script>
    function ConfirmDelete()
    {
        var x = confirm("Are you sure you want to delete?");
        if (x)
            return true;
        else
            return false;
    }
</script>
<?php $subAccounts = $block->getSubAccounts(); ?>
<?php if ($subAccounts && count($subAccounts)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('ID #') ?></th>
                <th scope="col" class="col prefix"><?php echo __('Prefix') ?></th>
                <th scope="col" class="col firstname"><?php echo __('FirstName') ?></th>
                <th scope="col" class="col lastname"><?php echo __('LastName') ?></th>
                <th scope="col" class="col email"><?php echo __('Email') ?></th>
                <th scope="col" class="col expire_date"><?php echo __('Date Of Birth ') ?></th>
                <th scope="col" class="col status"><?php echo __('Active') ?></th>
                <th scope="col" class="col action"><?php echo __('Action') ?></th>
                <th scope="col" class="col ">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($subAccounts as $subAccount): ?>
                <tr>
                    <td class="col id"><?php echo $subAccount->getEntityId() ?></td>
                    <td class="col prefix"><?php echo $subAccount->getPrefix() ?></td>
                    <td class="col firstname"><?php echo $subAccount->getFirstname() ?></td>
                    <td class="col lastname"><?php echo $subAccount->getLastname() ?></td>
                    <td class="col email"><?php echo $subAccount->getEmail() ?></td>
                    <td class="col date"><?php echo $block->formatDate($subAccount->getDob()) ?></td>
                    <td class="col status"><?php $status = $subAccount->getIsActiveSublogin() == 1 ? __('Yes') : __('No'); echo $status; ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <ul class="sub-ac">
                            <li>
                                <a href="<?php /* @escapeNotVerified */ echo $redirect . 'sublogins/account/edit' ?>" class="action view">
                                    <span><?php /* @escapeNotVerified */ echo __('Edit Account') ?></span>
                                </a>
                            </li>
                            <li>
                                <a  href="<?php /* @escapeNotVerified */echo $redirect . 'sublogins/account/delete/id/' . $subAccount->getId() ?>" onclick="return ConfirmDelete();" class="action delete">
                                    <span>Delete Account</span>
                                </a>
                            </li>
                            <?php if($subAccount->getIsActiveSublogin()) :  ?>
                                <li>
                                    <a  href="<?php /* @escapeNotVerified */echo $redirect . 'sublogins/account/deactive/deac/' . $subAccount->getId() ?>" class="action deactive">
                                        <span class="warning-subac">Deactive Account</span>
                                    </a>
                                </li>
                            <?php else : ?>
                                <li>
                                    <a  href="<?php /* @escapeNotVerified */echo $redirect . 'sublogins/account/active/ac/' . $subAccount->getId() ?>" class="action active">
                                        <span>Active Account</span>
                                    </a>
                                </li>
                            <?php endif; ?>

                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); // for display pager block which we create in block file.   ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('There are no sub account.'); ?></span></div>
<?php endif ?>



